name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./payment/pom.xml
          mvn clean package -f ./flightReservation/pom.xml
          mvn clean package -f ./user/pom.xml
          mvn clean package -f ./myPage/pom.xml
          mvn clean package -f ./flight/pom.xml
          mvn clean package -f ./lodging/pom.xml
          mvn clean package -f ./lodgingReservation/pom.xml

      - name: Docker Build and push for Payment
        uses: docker/build-push-action@v4
        with:
          context: ./payment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/payment:latest
            ghcr.io/${{ github.repository }}/payment:${{ github.ref_name }}
            
      - name: Docker Build and push for FlightReservation
        uses: docker/build-push-action@v4
        with:
          context: ./flightReservation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/flightreservation:latest
            ghcr.io/${{ github.repository }}/flightreservation:${{ github.ref_name }}
            
      - name: Docker Build and push for User
        uses: docker/build-push-action@v4
        with:
          context: ./user
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user:latest
            ghcr.io/${{ github.repository }}/user:${{ github.ref_name }}
            
      - name: Docker Build and push for MyPage
        uses: docker/build-push-action@v4
        with:
          context: ./myPage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/mypage:latest
            ghcr.io/${{ github.repository }}/mypage:${{ github.ref_name }}
            
      - name: Docker Build and push for Flight
        uses: docker/build-push-action@v4
        with:
          context: ./flight
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/flight:latest
            ghcr.io/${{ github.repository }}/flight:${{ github.ref_name }}
            
      - name: Docker Build and push for Lodging
        uses: docker/build-push-action@v4
        with:
          context: ./lodging
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/lodging:latest
            ghcr.io/${{ github.repository }}/lodging:${{ github.ref_name }}
            
      - name: Docker Build and push for LodgingReservation
        uses: docker/build-push-action@v4
        with:
          context: ./lodgingReservation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/lodgingreservation:latest
            ghcr.io/${{ github.repository }}/lodgingreservation:${{ github.ref_name }}
            
